function [state,options] = psoplotvelocity(options,state,flag)
% Plots the best, mean, and worst scores of particle swarm.

notinf = isfinite(state.Score) ;

if strcmp(flag,'init')
    set(gca,'NextPlot','add',...
        'XLabel',xlabel('Generation'),...
        'YLabel',ylabel('Velocity'))
    line(state.Generation,max(state.VelocityMag),...
        'Color','red',...
        'Tag','Max Velocities',...
        'Marker','.',...
        'MarkerSize',9,...
        'LineStyle','none')
    line(state.Generation,mean(state.VelocityMag(notinf)),...
        'Color','blue',...
        'Tag','Mean Velocities',...
        'Marker','.',...
        'MarkerSize',9,...
        'LineStyle','none')
    line(state.Generation,min(state.VelocityMag),...
        'Color','black',...
        'Tag','Min Velocities',...
        'Marker','.',...
        'MarkerSize',9,...
        'LineStyle','none')
    if(~isempty(options.VelocityLimit))
        line(state.Generation,sqrt(sum(options.VelocityLimit.^2)),...
            'Color','red',...
            'Tag','Limit',...
            'Marker','.',...
            'MarkerSize',1,...
            'LineStyle','-');
    end
elseif strcmp(flag,'done')
    legend({'Max Velocity','Mean Velocity', 'Min Velocity'})
else
    hmax = findobj(gca,'Tag','Max Velocities','Type','line') ;
    hmean = findobj(gca,'Tag','Mean Velocities','Type','line') ;
    hmin = findobj(gca,'Tag','Min Velocities','Type','line') ;
    hlim = findobj(gca,'Tag','Limit','Type','line') ;
    x = [get(hmean,'XData'), state.Generation] ;
    ymax = [get(hmax,'YData'), max(state.VelocityMag)] ;
    ymean = [get(hmean,'YData'), mean(state.VelocityMag(notinf))] ;
    ymin = [get(hmin,'YData'), min(state.VelocityMag)] ;
    limit = [get(hlim,'YData'), sqrt(sum(options.VelocityLimit.^2))] ;
    set(hmax,...
        'XData',x,...
        'YData',ymax)
    set(hmean,...
        'XData',x,...
        'YData',ymean)
    set(hmin,...
        'XData',x,...
        'YData',ymin)
    set(hlim,...
        'XData',x,...
        'YData',limit)
    titletxt = sprintf('Min: %g Mean: %g Max: %g',ymin(end),ymean(end),ymax(end)) ;
    title(titletxt)
end